@startuml


:Operator:
:Product:
:Driver:

left to right direction

  Operator -- (1. Geographical Visualization \n of Drivers) : (1) ask for visualization
  Product -up-- (1. Geographical Visualization \n of Drivers) : (2) analyze request \n and send collected information
  Product -up-- (2. Finding out best route) : (4) analyze requested route, \n return best route to driver
  Driver -- (2. Finding out best route) : (3) ask for best route \n from one coordinate to another
  
@enduml